(function(){
  "use strict";
  var U=window.EI_UTIL,S=window.EI_SUPABASE;
  var form=U.qs("#loginForm"),status=U.qs("#authStatus"),submit=U.qs("#loginSubmit"),google=U.qs("#googleSignIn"),continueBox=U.qs("#activeSession"),continueBtn=U.qs("#continueSession"),changeBtn=U.qs("#changeAccount"),password=U.qs("#password"),togglePassword=U.qs("#togglePassword"),reset=U.qs("#resetPassword");
  var recoveryMode=false;
  function announce(message,type){status.className="auth-status"+(type?" "+type:"");status.innerHTML=(type==="error"?U.icon("alert"):U.icon(type==="success"?"check":"user"))+"<span>"+U.escape(message)+"</span>";status.removeAttribute("hidden");}
  function busy(value,label){submit.disabled=!!value;google.disabled=!!value;submit.innerHTML=value?'<span class="ei-spinner" aria-hidden="true"></span><span>'+U.escape(label||"Validando…")+'</span>':'<span>Ingresar</span>'+U.icon("arrow");form.setAttribute("aria-busy",String(!!value));}
  function goPortal(){var profile=document.documentElement.dataset.layoutProfile||"",rootBase=document.documentElement.dataset.rootBase||"./",target=rootBase+"portal/";if(["ios","compact","square"].indexOf(profile)>=0)target=rootBase+"portal/"+profile+"/";location.href=target;}
  function showExisting(user){if(recoveryMode)return;S.profileFor(user).then(function(profile){S.saveProfile(profile);var initials=String(profile.name||"U").split(/\s+/).slice(0,2).map(function(x){return x.charAt(0);}).join("").toUpperCase();U.qs("[data-session-avatar]").textContent=initials;U.qs("[data-session-name]").textContent=profile.name;U.qs("[data-session-role]").textContent=profile.role;continueBox.removeAttribute("hidden");}).catch(function(error){announce(error.message,"error");});}
  function openRecovery(){
    if(recoveryMode)return;recoveryMode=true;continueBox.setAttribute("hidden","");form.setAttribute("hidden","");
    var panel=document.createElement("form");panel.id="passwordRecoveryForm";panel.className="auth-form";panel.innerHTML='<div class="auth-recovery-copy"><strong>Crear nueva contraseña</strong><span>El enlace fue validado. Use mínimo 10 caracteres y evite reutilizar la contraseña temporal.</span></div><label class="ei-field"><span>Nueva contraseña</span><input class="ei-input" name="newPassword" type="password" minlength="10" autocomplete="new-password" required></label><label class="ei-field"><span>Confirmar contraseña</span><input class="ei-input" name="confirmPassword" type="password" minlength="10" autocomplete="new-password" required></label><button class="ei-btn" type="submit">Guardar nueva contraseña</button>';
    form.parentNode.insertBefore(panel,status);panel.addEventListener("submit",function(event){event.preventDefault();var fd=new FormData(panel),next=String(fd.get("newPassword")||""),confirm=String(fd.get("confirmPassword")||"");if(next.length<10){announce("La nueva contraseña debe tener al menos 10 caracteres.","error");return;}if(next!==confirm){announce("Las contraseñas no coinciden.","error");return;}var button=panel.querySelector("button");button.disabled=true;button.textContent="Guardando…";S.state.auth.updatePassword(next).then(function(){announce("Contraseña actualizada. Abriendo el portal…","success");history.replaceState(null,"",location.pathname);setTimeout(goPortal,700);}).catch(function(error){button.disabled=false;button.textContent="Guardar nueva contraseña";announce(error.message||error,"error");});});
    announce("Escriba y confirme su nueva contraseña.");
  }
  S.init().then(function(){S.state.auth.onAuthStateChanged(function(user,event){if(event==="PASSWORD_RECOVERY"){openRecovery();return;}if(user)showExisting(user);});}).catch(function(error){announce("No fue posible iniciar Supabase: "+error.message,"error");});
  form.addEventListener("submit",function(event){event.preventDefault();var fd=new FormData(form),email=String(fd.get("email")||"").trim(),pass=String(fd.get("password")||"");if(!email||!pass){announce("Ingrese correo y contraseña.","error");return;}busy(true,"Validando acceso…");S.init().then(function(){return S.state.auth.signInWithEmailAndPassword(email,pass);}).then(function(result){return S.profileFor(result.user);}).then(function(profile){S.saveProfile(profile);announce("Acceso autorizado. Abriendo el portal…","success");setTimeout(goPortal,300);}).catch(function(error){announce((error&&error.message)||"No fue posible iniciar sesión.","error");busy(false);});});
  google.addEventListener("click",function(){busy(true,"Redirigiendo a Google…");S.init().then(function(){return S.state.auth.signInWithPopup();}).catch(function(error){announce((error&&error.message)||"No fue posible ingresar con Google.","error");busy(false);});});
  if(reset)reset.addEventListener("click",function(){var email=String(new FormData(form).get("email")||"").trim();if(!email){announce("Escriba su correo para enviar la recuperación.","error");return;}S.init().then(function(){return S.state.auth.sendPasswordResetEmail(email);}).then(function(){announce("Se envió el enlace de recuperación al correo indicado.","success");}).catch(function(error){announce(error.message||error,"error");});});
  continueBtn.addEventListener("click",goPortal);
  changeBtn.addEventListener("click",function(){S.init().then(function(){return S.state.auth.signOut();}).then(function(){S.clearProfile();continueBox.setAttribute("hidden","");announce("Sesión cerrada. Ingrese con otra cuenta.");});});
  togglePassword.addEventListener("click",function(){var show=password.type==="password";password.type=show?"text":"password";togglePassword.setAttribute("aria-label",show?"Ocultar contraseña":"Mostrar contraseña");togglePassword.textContent=show?"Ocultar":"Ver";password.focus();});
  window.EI_A11Y.bind(document);
})();
