(function(){
  "use strict";
  var U=window.EI_UTIL,F=window.EI_FIREBASE,cfg=window.EI_NOVA_CONFIG;
  var form=U.qs("#loginForm"),status=U.qs("#authStatus"),submit=U.qs("#loginSubmit"),google=U.qs("#googleSignIn"),continueBox=U.qs("#activeSession"),continueBtn=U.qs("#continueSession"),changeBtn=U.qs("#changeAccount"),password=U.qs("#password"),togglePassword=U.qs("#togglePassword");
  function announce(message,type){status.className="auth-status"+(type?" "+type:"");status.innerHTML=(type==="error"?U.icon("alert"):U.icon(type==="success"?"check":"user"))+"<span>"+U.escape(message)+"</span>";status.removeAttribute("hidden");}
  function busy(value,label){submit.disabled=!!value;google.disabled=!!value;submit.innerHTML=value?'<span class="ei-spinner" aria-hidden="true"></span><span>'+U.escape(label||"Validando…")+'</span>':'<span>Ingresar</span>'+U.icon("arrow");form.setAttribute("aria-busy",String(!!value));}
  function goPortal(){var profile=document.documentElement.dataset.layoutProfile||"",rootBase=document.documentElement.dataset.rootBase||"./",target=rootBase+"portal/";if(["ios","compact","square"].indexOf(profile)>=0)target=rootBase+"portal/"+profile+"/";location.href=target;}
  function showExisting(user){F.profileFor(user).then(function(profile){F.saveProfile(profile);var initials=String(profile.name||"U").split(/\s+/).slice(0,2).map(function(x){return x.charAt(0);}).join("").toUpperCase();U.qs("[data-session-avatar]").textContent=initials;U.qs("[data-session-name]").textContent=profile.name;U.qs("[data-session-role]").textContent=profile.role;continueBox.removeAttribute("hidden");}).catch(function(error){announce(error.message,"error");});}
  F.init().then(function(){F.state.auth.onAuthStateChanged(function(user){if(user)showExisting(user);});}).catch(function(error){announce("No fue posible iniciar Firebase: "+error.message,"error");});
  form.addEventListener("submit",function(event){event.preventDefault();var fd=new FormData(form),email=String(fd.get("email")||"").trim(),pass=String(fd.get("password")||""),remember=!!fd.get("remember");if(!email||!pass){announce("Ingrese correo y contraseña.","error");return;}busy(true,"Validando acceso…");F.init().then(function(){var persistence=remember?firebase.auth.Auth.Persistence.LOCAL:firebase.auth.Auth.Persistence.SESSION;return F.state.auth.setPersistence(persistence).then(function(){return F.state.auth.signInWithEmailAndPassword(email,pass);});}).then(function(result){return F.profileFor(result.user);}).then(function(profile){F.saveProfile(profile);announce("Acceso autorizado. Abriendo el portal…","success");setTimeout(goPortal,300);}).catch(function(error){announce((error&&error.message)||"No fue posible iniciar sesión.","error");busy(false);});});
  google.addEventListener("click",function(){busy(true,"Abriendo Google…");F.init().then(function(){return F.state.auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).then(function(){return F.state.auth.signInWithPopup(new firebase.auth.GoogleAuthProvider());});}).then(function(result){return F.profileFor(result.user);}).then(function(profile){F.saveProfile(profile);goPortal();}).catch(function(error){announce((error&&error.message)||"No fue posible ingresar con Google.","error");busy(false);});});
  continueBtn.addEventListener("click",goPortal);
  changeBtn.addEventListener("click",function(){F.init().then(function(){return F.state.auth.signOut();}).then(function(){F.clearProfile();continueBox.setAttribute("hidden","");announce("Sesión cerrada. Ingrese con otra cuenta.");});});
  togglePassword.addEventListener("click",function(){var show=password.type==="password";password.type=show?"text":"password";togglePassword.setAttribute("aria-label",show?"Ocultar contraseña":"Mostrar contraseña");togglePassword.textContent=show?"Ocultar":"Ver";password.focus();});
  window.EI_A11Y.bind(document);
})();
