(function(){
"use strict";
var cfg=(window.EI_NOVA_CONFIG&&window.EI_NOVA_CONFIG.drive)||{};
var token="",expiresAt=0,tokenClient=null,pending=null,cache={};
var TOKEN_KEY="ei_drive_token_v7",GRANT_KEY="ei_drive_grant_v7";
function configured(){return !!(cfg.googleClientId&&/\.apps\.googleusercontent\.com$/.test(cfg.googleClientId));}
function readToken(){try{var x=JSON.parse(sessionStorage.getItem(TOKEN_KEY)||"null");if(x&&x.token&&Number(x.expiresAt)>Date.now()+60000){token=x.token;expiresAt=Number(x.expiresAt);return token;}}catch(e){}return "";}
function saveToken(value,seconds){token=value;expiresAt=Date.now()+Math.max(60,Number(seconds||3600)-90)*1000;try{sessionStorage.setItem(TOKEN_KEY,JSON.stringify({token:token,expiresAt:expiresAt}));localStorage.setItem(GRANT_KEY,"1");}catch(e){}return token;}
function waitGoogle(){if(window.google&&google.accounts&&google.accounts.oauth2)return Promise.resolve();return new Promise(function(resolve,reject){var start=Date.now(),t=setInterval(function(){if(window.google&&google.accounts&&google.accounts.oauth2){clearInterval(t);resolve();}else if(Date.now()-start>15000){clearInterval(t);reject(new Error("No cargó Google Identity Services."));}},200);});}
function connect(interactive){if(readToken())return Promise.resolve(token);if(pending)return pending;if(!configured())return Promise.reject(new Error("El OAuth Client de Google Drive no está configurado."));if(!interactive)return Promise.reject(new Error("Conecte Google Drive para continuar."));pending=waitGoogle().then(function(){return new Promise(function(resolve,reject){tokenClient=google.accounts.oauth2.initTokenClient({client_id:cfg.googleClientId,scope:cfg.scope||"https://www.googleapis.com/auth/drive.file",callback:function(r){pending=null;if(r&&r.access_token)resolve(saveToken(r.access_token,r.expires_in));else reject(new Error((r&&(r.error_description||r.error))||"No se autorizó Drive."));},error_callback:function(e){pending=null;reject(new Error((e&&(e.message||e.type))||"No se abrió la autorización de Drive."));}});var known=false;try{known=localStorage.getItem(GRANT_KEY)==="1";}catch(e){}tokenClient.requestAccessToken({prompt:known?"":"consent"});});});return pending;}
function request(url,options){options=options||{};return connect(options.interactive!==false).then(function(access){var headers=Object.assign({},options.headers||{},{Authorization:"Bearer "+access});return fetch(url,Object.assign({},options,{headers:headers}));}).then(function(r){if(r.status===401){token="";expiresAt=0;try{sessionStorage.removeItem(TOKEN_KEY);}catch(e){}throw new Error("La autorización de Drive venció. Conecte Drive nuevamente.");}if(!r.ok)return r.text().then(function(t){throw new Error("Drive HTTP "+r.status+": "+t.slice(0,500));});if(r.status===204)return null;return r.json();});}
function qEscape(value){return String(value||"").replace(/\\/g,"\\\\").replace(/'/g,"\\'");}
function findFolder(name,parent){var q="name = '"+qEscape(name)+"' and mimeType = 'application/vnd.google-apps.folder' and trashed = false"+(parent?" and '"+qEscape(parent)+"' in parents":"");var url="https://www.googleapis.com/drive/v3/files?spaces=drive&fields=files(id,name)&pageSize=10&q="+encodeURIComponent(q);return request(url,{method:"GET"}).then(function(x){return x&&x.files&&x.files[0]||null;});}
function createFolder(name,parent){var body={name:name,mimeType:"application/vnd.google-apps.folder"};if(parent)body.parents=[parent];return request("https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}
function ensureFolder(name,parent){var key=(parent||"root")+"/"+name;if(cache[key])return Promise.resolve(cache[key]);return findFolder(name,parent).then(function(found){if(found){cache[key]=found;return found;}return createFolder(name,parent).then(function(created){cache[key]=created;return created;});});}
function ensurePath(parts){parts=(parts||[]).filter(Boolean);var parent=null,path=[];return parts.reduce(function(chain,name){return chain.then(function(){path.push(name);return ensureFolder(name,parent).then(function(folder){parent=folder.id;});});},Promise.resolve()).then(function(){return {folderId:parent,folderPath:path.join(" / ")};});}
function upload(file,options){options=options||{};if(!file)return Promise.reject(new Error("Seleccione un archivo."));var parts=[cfg.rootFolderName||"EVIDENCIAS_LOGISTICA_ELECTROINGENIERIA"].concat(options.path||[]);return ensurePath(parts).then(function(folder){var meta={name:options.fileName||file.name,mimeType:file.type||"application/octet-stream",parents:[folder.folderId]};var boundary="ei_"+Date.now()+"_"+Math.random().toString(36).slice(2);var body=new Blob(["--"+boundary+"\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n",JSON.stringify(meta),"\r\n--"+boundary+"\r\nContent-Type: "+(file.type||"application/octet-stream")+"\r\n\r\n",file,"\r\n--"+boundary+"--"],{type:"multipart/related; boundary="+boundary});return request("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,size,webViewLink,webContentLink,createdTime",{method:"POST",headers:{"Content-Type":"multipart/related; boundary="+boundary},body:body}).then(function(r){return {fileId:r.id,driveId:r.id,url:r.webViewLink||r.webContentLink||("https://drive.google.com/file/d/"+r.id+"/view"),driveUrl:r.webViewLink||r.webContentLink||("https://drive.google.com/file/d/"+r.id+"/view"),fileName:r.name,mimeType:r.mimeType,sizeBytes:Number(r.size||file.size||0),folder:folder.folderId,folderPath:folder.folderPath,uploadedAt:r.createdTime||new Date().toISOString()};});});}
function remove(fileId){if(!fileId)return Promise.resolve();return request("https://www.googleapis.com/drive/v3/files/"+encodeURIComponent(fileId),{method:"DELETE"});}
function status(){return {configured:configured(),connected:!!readToken(),expiresAt:expiresAt};}
window.EI_DRIVE={connect:connect,upload:upload,remove:remove,ensurePath:ensurePath,status:status,clear:function(){token="";expiresAt=0;cache={};try{sessionStorage.removeItem(TOKEN_KEY);}catch(e){}}};
})();
