(function(){
"use strict";
var appEl=document.getElementById("app"), cfg=window.EI_CURRENT_MODULE||{}, root=window.EI_APP_ROOT||"../../", mods=window.EI_V2_MODULES||[], labels=window.EI_V2_ROUTE_LABELS||{};
var settings=window.erpSettings||{}, state={user:null,profile:null,role:"",catalog:null,rows:[],loading:false,search:""};
var ADMIN_ROLES=["super_admin","admin","gerencia","manager","jefe_logistico","auditoria"];
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
function norm(v){return String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_");}
function canWrite(meta){if(meta&&meta.readonly)return false;var role=norm(state.role);if(meta&&Array.isArray(meta.writeRoles))return meta.writeRoles.map(norm).indexOf(role)>=0;return ADMIN_ROLES.indexOf(role)>=0;}
function route(){var q=new URLSearchParams(location.search).get("route");return cfg.routes&&cfg.routes.indexOf(q)>=0?q:(cfg.defaultRoute||cfg.routes[0]);}
function routeUrl(m,r){return m.url+(r?"?route="+encodeURIComponent(r):"");}
function nowServer(){return firebase.firestore.FieldValue.serverTimestamp();}
function id(){return (crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2));}
function display(v){if(v==null)return "";if(v&&typeof v.toDate==="function")return v.toDate().toLocaleString("es-CO");if(typeof v==="object")return JSON.stringify(v);return String(v);}
function moduleGroups(){var groups={};mods.forEach(function(m){(groups[m.group]||(groups[m.group]=[])).push(m);});return groups;}
function signIn(){var provider=new firebase.auth.GoogleAuthProvider();firebase.auth().signInWithPopup(provider).catch(showError);}
function signOut(){firebase.auth().signOut();}
function showError(e){console.error(e);alert((e&&e.message)||String(e));}
async function initFirebase(){if(!firebase.apps.length)firebase.initializeApp(window.firebaseConfig);if(settings.appCheckSiteKey&&firebase.appCheck){try{firebase.appCheck().activate(new firebase.appCheck.ReCaptchaEnterpriseProvider(settings.appCheckSiteKey),true);}catch(e){console.warn("App Check no inicializado",e);}}firebase.firestore().settings({ignoreUndefinedProperties:true});try{await firebase.firestore().enablePersistence({synchronizeTabs:true});}catch(e){if(!e||!["failed-precondition","unimplemented"].includes(e.code))console.warn("Persistencia offline no disponible",e);}}
async function profileFor(user){var db=firebase.firestore(), byUid=await db.collection("users").doc(user.uid).get();if(byUid.exists)return byUid.data();var byEmail=await db.collection("users").doc(user.email||"_").get();return byEmail.exists?byEmail.data():{};}
function renderSignin(){appEl.innerHTML='<main class="erp-signin"><section><img src="'+esc(root+'shared/assets/logo-electroingenieria.jpeg')+'" alt="Electroingeniería"><h1>EI ERP V5</h1><p>Ingrese con la cuenta corporativa autorizada.</p><button class="erp-btn" id="erpSignIn">Ingresar con Google</button></section></main>';document.getElementById("erpSignIn").onclick=signIn;}
function nav(){if(window.EI_NAV){window.EI_NAV.setContext({role:state.role,module:cfg.id,route:route()});return window.EI_NAV.renderSidebar({role:state.role,currentModule:cfg.id,currentRoute:route()});}return "";}
function tabs(){var routes=(cfg.routes||[]);if(window.EI_NAV){var visible=window.EI_NAV.accessibleModules({role:state.role,currentModule:cfg.id,currentRoute:route()}).filter(function(m){return m.id===cfg.id;})[0];routes=visible?visible.routes:[];}return routes.map(function(r){return '<a class="'+(route()===r?'active':'')+'" href="?route='+encodeURIComponent(r)+'">'+esc(labels[r]||r)+'</a>';}).join('');}
function shell(body){var p=state.profile||{}, uname=p.name||p.displayName||state.user.displayName||state.user.email||"Usuario";if(window.EI_NAV)window.EI_NAV.setContext({role:state.role,module:cfg.id,route:route()});appEl.innerHTML='<div class="erp-layout" id="erpLayout"><aside class="erp-sidebar"><div class="erp-brand"><img src="'+esc(root+'shared/assets/logo-electroingenieria.jpeg')+'" alt="Electroingeniería"><div><strong>EI ERP V5</strong><small>Operación conectada</small></div></div><button class="erp-command" id="erpCommand" type="button"><span><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5" fill="none" stroke="currentColor" stroke-width="2"/><path d="m16 16 4 4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></span><b>Buscar módulo o función</b><kbd>Ctrl K</kbd></button><nav class="erp-nav" aria-label="Navegación principal">'+nav()+'</nav></aside><main class="erp-main"><header class="erp-topbar"><div class="erp-title-wrap"><button class="erp-icon-btn erp-mobile-nav" id="erpMobileNav" aria-label="Abrir navegación">☰</button><div><div class="erp-breadcrumb">'+esc(cfg.group||"ERP")+' / '+esc(cfg.short||cfg.title||"Módulo")+'</div><h1>'+esc(cfg.title||"ERP")+'</h1><p>'+esc(cfg.description||"")+'</p></div></div><div class="erp-user"><span><b>'+esc(uname)+'</b><br>'+esc(state.role||"sin rol")+'</span><button class="erp-btn secondary" id="erpSignOut">Salir</button></div></header><section class="erp-content"><nav class="erp-tabs">'+tabs()+'</nav>'+body+'</section></main></div>';document.getElementById("erpSignOut").onclick=signOut;var command=document.getElementById("erpCommand");if(command)command.onclick=function(){if(window.EI_UX)window.EI_UX.openCommandPalette();};var mobile=document.getElementById("erpMobileNav");if(mobile)mobile.onclick=function(){document.getElementById("erpLayout").classList.toggle("mobile-nav-open");};if(window.EI_NAV)window.EI_NAV.bind(document);}
function hero(meta){return '<section class="erp-hero"><div><h2>'+esc(meta.title)+'</h2><p>'+esc(meta.description)+'</p></div>'+(meta.readonly||!canWrite(meta)?'':'<button class="erp-btn secondary" id="erpCreate">'+esc(meta.createLabel||'Nuevo registro')+'</button>')+'</section>';}
function columnKeys(rows){var preferred=["code","productCode","name","title","status","warehouseCode","locationCode","quantity","uom","sourceDocument","createdAt","createdByName"];var keys={};rows.forEach(function(r){Object.keys(r).forEach(function(k){if(["tenantId","updatedAt","updatedBy","payload","before","after"].indexOf(k)<0)keys[k]=1;});});return preferred.filter(function(k){return keys[k];}).concat(Object.keys(keys).filter(function(k){return preferred.indexOf(k)<0;}).slice(0,7)).slice(0,10);}
function table(meta,rows){var filtered=rows.filter(function(r){return !state.search||JSON.stringify(r).toLowerCase().indexOf(state.search.toLowerCase())>=0;}), keys=columnKeys(filtered.length?filtered:rows);if(!rows.length)return '<div class="erp-card erp-empty">Todavía no existen registros en <b>'+esc(meta.collection)+'</b>.</div>';return '<div class="erp-table-wrap"><table class="erp-table"><thead><tr>'+keys.map(function(k){return '<th>'+esc(k)+'</th>';}).join('')+'</tr></thead><tbody>'+filtered.map(function(r){return '<tr>'+keys.map(function(k){var v=display(r[k]);return '<td title="'+esc(v)+'">'+(k==="status"?'<span class="erp-pill">'+esc(v)+'</span>':esc(v.length>90?v.slice(0,90)+'…':v))+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';}
function metrics(rows){var statuses={};rows.forEach(function(r){var s=r.status||r.result||r.movementType||"SIN_ESTADO";statuses[s]=(statuses[s]||0)+1;});var top=Object.keys(statuses).sort(function(a,b){return statuses[b]-statuses[a];}).slice(0,3);return '<section class="erp-grid"><article class="erp-card erp-kpi"><span>Registros cargados</span><strong>'+rows.length+'</strong><small>Últimos 100</small></article>'+top.map(function(s){return '<article class="erp-card erp-kpi"><span>'+esc(s)+'</span><strong>'+statuses[s]+'</strong><small>Registros</small></article>';}).join('')+'</section>';}
async function loadRows(meta){state.loading=true;renderLoading(meta);var q=firebase.firestore().collection(meta.collection);if(meta.filter){Object.keys(meta.filter).forEach(function(k){q=q.where(k,"==",meta.filter[k]);});}q=q.orderBy("createdAt","desc").limit(100);try{var snap=await q.get();state.rows=snap.docs.map(function(d){return Object.assign({id:d.id},d.data());});}catch(e){console.warn("Consulta ordenada falló; usando consulta simple",e);try{var simple=await firebase.firestore().collection(meta.collection).limit(100).get();state.rows=simple.docs.map(function(d){return Object.assign({id:d.id},d.data());}).filter(function(r){return !meta.filter||Object.keys(meta.filter).every(function(k){return r[k]===meta.filter[k];});});}catch(e2){showError(e2);state.rows=[];}}state.loading=false;renderRoute();}
function renderLoading(meta){shell(hero(meta)+'<div class="erp-card erp-empty">Cargando información…</div>');}
function renderRoute(){var r=route(), meta=state.catalog[r];if(!meta){shell('<div class="erp-notice danger">Ruta ERP no configurada: '+esc(r)+'</div>');return;}var body=hero(meta)+metrics(state.rows)+'<div class="erp-toolbar"><input id="erpSearch" class="erp-search" placeholder="Buscar en los registros" value="'+esc(state.search)+'"><div class="erp-toolbar-actions"><button class="erp-btn secondary" id="erpExport">Exportar CSV</button><button class="erp-btn secondary" id="erpRefresh">Actualizar</button></div></div>'+table(meta,state.rows);shell(body);var create=document.getElementById("erpCreate");if(create)create.onclick=function(){openForm(meta);};document.getElementById("erpRefresh").onclick=function(){loadRows(meta);};var exportBtn=document.getElementById("erpExport");if(exportBtn)exportBtn.onclick=function(){exportCsv(meta,state.rows);};document.getElementById("erpSearch").oninput=function(e){state.search=e.target.value;var pos=e.target.selectionStart;renderRoute();setTimeout(function(){var s=document.getElementById("erpSearch");if(s){s.focus();s.setSelectionRange(pos,pos);}},0);};}
function exportCsv(meta,rows){if(!rows.length){alert("No hay registros para exportar.");return;}var keys=columnKeys(rows),quote=function(v){return '"'+String(display(v)).replace(/"/g,'""')+'"';},csv='\ufeff'+keys.map(quote).join(';')+'\n'+rows.map(function(r){return keys.map(function(k){return quote(r[k]);}).join(';');}).join('\n'),blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=(meta.collection||"erp")+"_"+new Date().toISOString().slice(0,10)+".csv";a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);writeAudit("EXPORT",meta.collection,"CSV",{route:route(),rows:rows.length});}
function fieldHtml(f){var name=f[0],label=f[1],kind=f[2],required=f[3], options=kind.indexOf("select:")===0?kind.slice(7).split(","):null;if(options)return '<label class="erp-field"><span>'+esc(label)+(required?' *':'')+'</span><select name="'+esc(name)+'" '+(required?'required':'')+'><option value="">Seleccione</option>'+options.map(function(o){return '<option>'+esc(o)+'</option>';}).join('')+'</select></label>';if(kind==="checkbox")return '<label class="erp-field checkbox"><input type="checkbox" name="'+esc(name)+'"><span>'+esc(label)+'</span></label>';return '<label class="erp-field"><span>'+esc(label)+(required?' *':'')+'</span><input type="'+esc(kind||"text")+'" name="'+esc(name)+'" '+(required?'required':'')+'></label>';}
function openForm(meta){var fields=meta.fields||[];var modal=document.createElement("div");modal.className="erp-modal";modal.innerHTML='<section class="erp-modal-card"><div class="erp-modal-head"><h2>Nuevo · '+esc(meta.title)+'</h2><button class="erp-btn secondary" type="button" id="erpClose">Cerrar</button></div><div class="erp-notice">El registro quedará identificado con usuario, empresa, sede, fecha y evento de auditoría.</div><form id="erpForm"><div class="erp-form-grid">'+fields.map(fieldHtml).join('')+'</div><button class="erp-btn" type="submit">Guardar</button></form></section>';document.body.appendChild(modal);document.getElementById("erpClose").onclick=function(){modal.remove();};document.getElementById("erpForm").onsubmit=async function(e){e.preventDefault();var fd=new FormData(e.target),data={idempotencyKey:id(),tenantId:settings.tenantId||"electroingenieria",companyCode:settings.companyCode||"EI",siteCode:settings.defaultSiteCode||"TULUA",createdAt:nowServer(),createdBy:state.user.uid,createdByName:state.profile.name||state.user.displayName||state.user.email,status:"ACTIVE"};fields.forEach(function(f){var k=f[0],kind=f[2];if(kind==="checkbox")data[k]=!!fd.get(k);else if(kind==="number")data[k]=Number(fd.get(k)||0);else data[k]=String(fd.get(k)||"").trim();});if(meta.filter)Object.assign(data,meta.filter);try{var result=null;if(meta.callableCreate){var callableData=Object.assign({},data);delete callableData.createdAt;delete callableData.createdByName;var callable=firebase.functions().httpsCallable(meta.callableCreate);result=(await callable(callableData)).data||{};}else{await firebase.firestore().collection(meta.collection).doc(data.idempotencyKey).set(data);}await writeAudit(meta.callableCreate?"EXECUTE":"CREATE",meta.collection,result&&result.id||data.idempotencyKey,{route:route(),callable:meta.callableCreate||""});modal.remove();if(result&&result.message)alert(result.message);loadRows(meta);}catch(err){showError(err);}};}
async function writeAudit(action,resource,resourceId,details){try{await firebase.firestore().collection("erp_access_events").add({tenantId:settings.tenantId||"electroingenieria",action:action,resource:resource,resourceId:resourceId,details:details||{},trustLevel:"CLIENT",source:"CLIENT_UI",createdAt:nowServer(),createdBy:state.user.uid,createdByName:state.user.email});}catch(e){console.warn("Auditoría cliente no registrada",e);}}
async function start(){await initFirebase();state.catalog=await fetch(root+'shared/json/enterprise-catalog.json?v=5.0.0').then(function(r){if(!r.ok)throw new Error("No cargó catálogo ERP");return r.json();});firebase.auth().onAuthStateChanged(async function(user){state.user=user;if(!user){renderSignin();return;}try{state.profile=await profileFor(user);state.role=state.profile.role||state.profile.rol||"usuario";await writeAudit("LOGIN_VIEW",cfg.id,route(),{});await loadRows(state.catalog[route()]);}catch(e){showError(e);}});}
start().catch(showError);
})();
