(function(){
"use strict";
var app=document.getElementById("app"),cfg=window.EI_CURRENT_MODULE||{},root=window.EI_APP_ROOT||"../../",mods=window.EI_V2_MODULES||[],labels=window.EI_V2_ROUTE_LABELS||{};
var CORE=window.EI_SUPABASE,COMPAT=window.EI_SUPABASE_COMPAT,settings=window.erpSettings||{};
var state={session:null,user:null,profile:null,role:"",db:null,catalog:null,rows:[],search:"",loading:false};
var ADMIN=["super_admin","super_administrador","admin","administrador","gerencia","manager","jefe_logistico","auditoria"];
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
function norm(v){return String(v||"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g,"_");}
function uid(){try{return crypto.randomUUID();}catch(e){return Date.now().toString(36)+Math.random().toString(36).slice(2);}}
function route(){var q=new URLSearchParams(location.search).get("route");return cfg.routes&&cfg.routes.indexOf(q)>=0?q:(cfg.defaultRoute||(cfg.routes||[])[0]);}
function display(v){if(v==null)return "";if(v&&typeof v.toDate==="function")v=v.toDate();if(typeof v==="string"&&/^\d{4}-\d{2}-\d{2}T/.test(v)){var d=new Date(v);if(!isNaN(d))return d.toLocaleString("es-CO");}if(typeof v==="object")return JSON.stringify(v);return String(v);}
function canWrite(meta){if(!meta||meta.readonly)return false;var role=norm(state.role);if(Array.isArray(meta.writeRoles))return meta.writeRoles.map(norm).indexOf(role)>=0;return ADMIN.indexOf(role)>=0;}
function showError(e){console.error(e);alert((e&&e.message)||String(e));}
function signOut(){CORE.state.auth.signOut().finally(function(){CORE.clearProfile();location.href=new URL("../index.html",root).href;});}
function nav(){if(window.EI_NAV){window.EI_NAV.setContext({role:state.role,module:cfg.id,route:route()});return window.EI_NAV.renderSidebar({role:state.role,currentModule:cfg.id,currentRoute:route()});}return "";}
function tabs(){var routes=cfg.routes||[];return routes.map(function(r){return '<a class="'+(route()===r?'active':'')+'" href="?route='+encodeURIComponent(r)+'">'+esc(labels[r]||r)+'</a>';}).join("");}
function shell(body){var name=state.profile.name||state.user.displayName||state.user.email||"Usuario";app.innerHTML='<div class="erp-layout" id="erpLayout"><aside class="erp-sidebar"><div class="erp-brand"><img src="'+esc(root+'shared/assets/logo-electroingenieria.jpeg')+'" alt="Electroingeniería"><div><strong>EI ERP Nova</strong><small>Supabase + Drive</small></div></div><button class="erp-command" id="erpCommand" type="button"><span>⌕</span><b>Buscar módulo o función</b><kbd>Ctrl K</kbd></button><nav class="erp-nav" aria-label="Navegación principal">'+nav()+'</nav></aside><main class="erp-main"><header class="erp-topbar"><div class="erp-title-wrap"><button class="erp-icon-btn erp-mobile-nav" id="erpMobileNav" aria-label="Abrir navegación">☰</button><div><div class="erp-breadcrumb">'+esc(cfg.group||"ERP")+' / '+esc(cfg.short||cfg.title||"Módulo")+'</div><h1>'+esc(cfg.title||"ERP")+'</h1><p>'+esc(cfg.description||"")+'</p></div></div><div class="erp-user"><span><b>'+esc(name)+'</b><br>'+esc(state.role||"sin rol")+'</span><button class="erp-btn secondary" id="erpSignOut">Salir</button></div></header><section class="erp-content"><nav class="erp-tabs">'+tabs()+'</nav>'+body+'</section></main></div>';
 document.getElementById("erpSignOut").onclick=signOut;var command=document.getElementById("erpCommand");if(command)command.onclick=function(){if(window.EI_UX)window.EI_UX.openCommandPalette();};var mobile=document.getElementById("erpMobileNav");if(mobile)mobile.onclick=function(){document.getElementById("erpLayout").classList.toggle("mobile-nav-open");};if(window.EI_NAV)window.EI_NAV.bind(document);
}
function hero(meta){return '<section class="erp-hero"><div><h2>'+esc(meta.title)+'</h2><p>'+esc(meta.description||"")+'</p></div>'+(canWrite(meta)?'<button class="erp-btn secondary" id="erpCreate">'+esc(meta.createLabel||"Nuevo registro")+'</button>':'')+'</section>';}
function keys(rows){var skip=["rawData","raw_data","payload","before","after","tenantId"],preferred=["code","productCode","name","title","status","warehouseCode","locationCode","quantity","uom","sourceDocument","createdAt","createdByName"],found={};rows.forEach(function(r){Object.keys(r||{}).forEach(function(k){if(skip.indexOf(k)<0)found[k]=1;});});return preferred.filter(function(k){return found[k];}).concat(Object.keys(found).filter(function(k){return preferred.indexOf(k)<0;}).slice(0,8)).slice(0,11);}
function table(meta,rows){var term=norm(state.search),filtered=rows.filter(function(r){return !term||norm(JSON.stringify(r)).indexOf(term)>=0;}),cols=keys(filtered.length?filtered:rows);if(!rows.length)return '<div class="erp-card erp-empty">Todavía no existen registros.</div>';return '<div class="erp-table-wrap"><table class="erp-table"><thead><tr>'+cols.map(function(k){return '<th>'+esc(k)+'</th>';}).join('')+'</tr></thead><tbody>'+filtered.map(function(r){return '<tr>'+cols.map(function(k){var v=display(r[k]);return '<td title="'+esc(v)+'">'+(k==="status"?'<span class="erp-pill">'+esc(v)+'</span>':esc(v.length>100?v.slice(0,100)+'…':v))+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';}
function metrics(rows){var states={};rows.forEach(function(r){var k=r.status||r.result||r.movementType||"SIN_ESTADO";states[k]=(states[k]||0)+1;});var top=Object.keys(states).sort(function(a,b){return states[b]-states[a];}).slice(0,3);return '<section class="erp-grid"><article class="erp-card erp-kpi"><span>Registros</span><strong>'+rows.length+'</strong><small>Vista actual</small></article>'+top.map(function(k){return '<article class="erp-card erp-kpi"><span>'+esc(k)+'</span><strong>'+states[k]+'</strong><small>Registros</small></article>';}).join('')+'</section>';}
function renderLoading(meta){shell(hero(meta)+'<div class="erp-card erp-empty">Cargando información…</div>');}
function query(meta){var q=state.db.collection(meta.collection);Object.keys(meta.filter||{}).forEach(function(k){q=q.where(k,"==",meta.filter[k]);});return q.orderBy("createdAt","desc").limit(250).get().catch(function(){return state.db.collection(meta.collection).limit(250).get();}).then(function(s){return s.docs.map(function(d){return Object.assign({id:d.id},d.data());});});}
function load(meta){if(!meta)return Promise.reject(new Error("Ruta sin configuración."));state.loading=true;renderLoading(meta);return query(meta).then(function(rows){state.rows=rows;state.loading=false;render(meta);}).catch(function(e){state.loading=false;showError(e);shell(hero(meta)+'<div class="erp-notice danger">'+esc(e.message||e)+'</div>');});}
function render(meta){var body=hero(meta)+metrics(state.rows)+'<div class="erp-toolbar"><input id="erpSearch" class="erp-search" placeholder="Buscar por nombre, código, documento o estado" value="'+esc(state.search)+'"><div class="erp-toolbar-actions"><button class="erp-btn secondary" id="erpExport">Exportar CSV</button><button class="erp-btn secondary" id="erpRefresh">Actualizar</button></div></div>'+table(meta,state.rows);shell(body);var c=document.getElementById("erpCreate");if(c)c.onclick=function(){openForm(meta);};document.getElementById("erpRefresh").onclick=function(){load(meta);};document.getElementById("erpExport").onclick=function(){exportCsv(meta,state.rows);};document.getElementById("erpSearch").oninput=function(e){state.search=e.target.value;render(meta);setTimeout(function(){var x=document.getElementById("erpSearch");if(x)x.focus();},0);};}
function fieldHtml(f){var name=f[0],label=f[1],kind=f[2]||"text",required=f[3],opts=kind.indexOf("select:")===0?kind.slice(7).split(","):null;if(opts)return '<label class="erp-field"><span>'+esc(label)+(required?' *':'')+'</span><select name="'+esc(name)+'" '+(required?'required':'')+'><option value="">Seleccione</option>'+opts.map(function(o){return '<option>'+esc(o)+'</option>';}).join('')+'</select></label>';if(kind==="checkbox")return '<label class="erp-field checkbox"><input type="checkbox" name="'+esc(name)+'"><span>'+esc(label)+'</span></label>';return '<label class="erp-field"><span>'+esc(label)+(required?' *':'')+'</span><input type="'+esc(kind)+'" name="'+esc(name)+'" '+(required?'required':'')+'></label>';}
function openForm(meta){var fields=meta.fields||[],modal=document.createElement("div");modal.className="erp-modal";modal.innerHTML='<section class="erp-modal-card"><div class="erp-modal-head"><h2>Nuevo · '+esc(meta.title)+'</h2><button class="erp-btn secondary" id="erpClose" type="button">Cerrar</button></div><div class="erp-notice">El registro se guardará en Supabase con usuario, fecha y trazabilidad.</div><form id="erpForm"><div class="erp-form-grid">'+fields.map(fieldHtml).join('')+'</div><button class="erp-btn" type="submit">Guardar</button></form></section>';document.body.appendChild(modal);document.getElementById("erpClose").onclick=function(){modal.remove();};document.getElementById("erpForm").onsubmit=function(e){e.preventDefault();var fd=new FormData(e.target),idempotency=uid(),data={idempotencyKey:idempotency,tenantId:settings.tenantId||"electroingenieria",companyCode:"EI",siteCode:"TULUA",createdAt:new Date().toISOString(),createdBy:state.profile.uid,createdByName:state.profile.name,status:"ACTIVE"};fields.forEach(function(f){var k=f[0],kind=f[2]||"text";data[k]=kind==="checkbox"?!!fd.get(k):kind==="number"?Number(fd.get(k)||0):String(fd.get(k)||"").trim();});Object.assign(data,meta.filter||{});state.db.collection(meta.collection).doc(idempotency).set(data).then(function(){return audit("CREATE",meta.collection,idempotency,{route:route()});}).then(function(){modal.remove();return load(meta);}).catch(showError);};}
function audit(action,resource,resourceId,details){return state.db.collection("erp_access_events").add({action:action,resource:resource,resourceId:resourceId,details:details||{},source:"SUPABASE_UI",createdAt:new Date().toISOString(),createdBy:state.profile.uid,createdByName:state.profile.name}).catch(function(e){console.warn("Auditoría no registrada",e);});}
function exportCsv(meta,rows){if(!rows.length)return alert("No hay registros para exportar.");var cols=keys(rows),quote=function(v){return '"'+display(v).replace(/"/g,'""')+'"';},csv='\ufeff'+cols.map(quote).join(';')+'\n'+rows.map(function(r){return cols.map(function(k){return quote(r[k]);}).join(';');}).join('\n'),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download=(meta.collection||"erp")+"_"+new Date().toISOString().slice(0,10)+".csv";a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);audit("EXPORT",meta.collection,"CSV",{rows:rows.length});}
function start(){return Promise.all([CORE.requireSession({loginUrl:new URL("../index.html",root).href}),COMPAT.create(),fetch(root+'shared/json/enterprise-catalog.json?v=7.0.0').then(function(r){if(!r.ok)throw new Error("No cargó el catálogo ERP");return r.json();})]).then(function(v){state.session=v[0];state.user=v[0].user;state.profile=v[0].profile;state.role=state.profile.role;state.db=v[1].db;state.catalog=v[2];return audit("MODULE_OPEN",cfg.id,route(),{}).then(function(){return load(state.catalog[route()]);});});}
start().catch(function(e){showError(e);app.innerHTML='<main class="erp-signin"><section><h1>No fue posible abrir el módulo</h1><p>'+esc(e.message||e)+'</p><a class="erp-btn" href="'+esc(new URL('../index.html',root).href)+'">Volver al acceso</a></section></main>';});
})();
